/* Generated by tools/generate_terrain_artifacts.py; Fast Reflex v2 slip frozen Vela U55. */
#ifndef FAST_REFLEX_SLIP_V2_U55_TFLM_MODEL_INT8X8_H
#define FAST_REFLEX_SLIP_V2_U55_TFLM_MODEL_INT8X8_H
#include <stdint.h>
#ifdef CY_ML_MODEL_MEM
extern const uint8_t FAST_REFLEX_SLIP_V2_U55_model_bin[];
#else
extern uint8_t FAST_REFLEX_SLIP_V2_U55_model_bin[];
#endif
#define FAST_REFLEX_SLIP_V2_U55_MODEL_BIN_LEN (6272u)
#define FAST_REFLEX_SLIP_V2_U55_ARENA_SIZE (8192u)
#endif
