/* Generated by tools/generate_terrain_artifacts.py; fast1000, Vela ethos-u55-128. */
#ifndef TERRAIN_FAST1000_U55_TFLM_MODEL_INT8X8_H
#define TERRAIN_FAST1000_U55_TFLM_MODEL_INT8X8_H
#include <stdint.h>
#ifdef CY_ML_MODEL_MEM
extern const uint8_t TERRAIN_FAST1000_U55_model_bin[];
#else
extern uint8_t TERRAIN_FAST1000_U55_model_bin[];
#endif
#define TERRAIN_FAST1000_U55_MODEL_BIN_LEN (7776u)
#define TERRAIN_FAST1000_U55_ARENA_SIZE (4096u)
#endif
