/* Generated by tools/generate_terrain_artifacts.py; frozen Terrain v4 raw strict-INT8. */
#ifndef TERRAIN_CAUSAL_WINDOW_V4_CPU_TFLM_MODEL_INT8X8_H
#define TERRAIN_CAUSAL_WINDOW_V4_CPU_TFLM_MODEL_INT8X8_H
#include <stdint.h>
#ifdef CY_ML_MODEL_MEM
extern const uint8_t TERRAIN_CAUSAL_WINDOW_V4_CPU_model_bin[];
#else
extern uint8_t TERRAIN_CAUSAL_WINDOW_V4_CPU_model_bin[];
#endif
#define TERRAIN_CAUSAL_WINDOW_V4_CPU_MODEL_BIN_LEN (6688u)
#define TERRAIN_CAUSAL_WINDOW_V4_CPU_ARENA_SIZE (8192u)
#endif
