/* Generated by tools/generate_terrain_artifacts.py; fast1000 raw strict-INT8 TFLite. */
#ifndef TERRAIN_FAST1000_CPU_TFLM_MODEL_INT8X8_H
#define TERRAIN_FAST1000_CPU_TFLM_MODEL_INT8X8_H
#include <stdint.h>
#ifdef CY_ML_MODEL_MEM
extern const uint8_t TERRAIN_FAST1000_CPU_model_bin[];
#else
extern uint8_t TERRAIN_FAST1000_CPU_model_bin[];
#endif
#define TERRAIN_FAST1000_CPU_MODEL_BIN_LEN (7048u)
#define TERRAIN_FAST1000_CPU_ARENA_SIZE (8192u)
#endif
