/***************************************************************************//**
* \file TEST_MODEL_tflm_model_int16x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains TEST_MODEL model data.
* Date: 2025-07-24 13:17:24.186403
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8804 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15478
    ml-coretools-tflm-qemu-images 3.1.0.15478
*/

#ifndef TEST_MODEL_TFLM_MODEL_INT16X8_H
#define TEST_MODEL_TFLM_MODEL_INT16X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t TEST_MODEL_model_bin[];
#else
extern uint8_t TEST_MODEL_model_bin[];
#endif // CY_ML_MODEL_MEM
#define TEST_MODEL_MODEL_BIN_LEN (88448u)
#define TEST_MODEL_ARENA_SIZE (107520u)

#endif // TEST_MODEL_TFLM_MODEL_INT16X8_H

