/***************************************************************************//**
* \file TEST_MODEL_tflm_y_data_int16x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the TEST_MODEL model in int16x8 representation.
* Date: 2025-06-20 17:08:20.793523
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_TFLM_Y_DATA_INT16X8_H
#define TEST_MODEL_TFLM_Y_DATA_INT16X8_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_y_data_bin[];
#define TEST_MODEL_Y_DATA_BIN_LEN (2000)

#endif // TEST_MODEL_TFLM_Y_DATA_INT16X8_H

