/***************************************************************************//**
* \file TEST_MODEL_tflm_x_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the TEST_MODEL model in float representation.
* Date: 2025-06-20 17:08:20.290673
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_TFLM_X_DATA_FLOAT_H
#define TEST_MODEL_TFLM_X_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_x_data_bin[];
#define TEST_MODEL_X_DATA_BIN_LEN (313616)

#endif // TEST_MODEL_TFLM_X_DATA_FLOAT_H

