#!/usr/bin/env python3
"""Generate reproducible CM55/U55 model arrays and one fixed terrain test tensor."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import struct
import subprocess
from pathlib import Path

import numpy as np


PROJECT = Path(__file__).resolve().parents[1]
REPO = PROJECT.parents[2]
SIMULATION = REPO / "simulation"
MODEL = (
    SIMULATION
    / "outputs/terrain_dataset_v1_expanded_int8_seed_20260809/noisy_fusion_int8.tflite"
)
DATASET = SIMULATION / "outputs/terrain_dataset_v1_expanded/dataset_noisy.npz"
NORMALIZATION = (
    SIMULATION
    / "outputs/terrain_dataset_v1_expanded_cnn_seed_20260809_e120/normalization.json"
)
MODEL_SHA256 = "f5d34f48b765d89f61cebe7e15eb9ee27a78b1c823950bca67043b6d4fa96df4"
DATASET_SHA256 = "ee84861570a1ae1244c54957219b9896c29a1756be97d4d02353f9699ac264ec"
SAMPLE_INDEX = 878
CLASS_NAMES = ("concrete", "marble", "ice", "sand")
MODEL_DIR = PROJECT / "proj_cm55/mtb_ml_gen/mtb_ml_models"
DATA_DIR = PROJECT / "proj_cm55/mtb_ml_gen/mtb_ml_regression_data"
REPORT_DIR = PROJECT / "deployment"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def c_bytes(values: bytes, columns: int = 16) -> str:
    rows = []
    for offset in range(0, len(values), columns):
        row = values[offset : offset + columns]
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in row) + ",")
    return "\n".join(rows)


def write_model(name: str, model: bytes, arena_size: int, provenance: str) -> None:
    stem = f"{name}_tflm_model_int8x8"
    guard = f"{stem.upper()}_H"
    header = f"""/* Generated by tools/generate_terrain_artifacts.py; {provenance}. */
#ifndef {guard}
#define {guard}
#include <stdint.h>
#ifdef CY_ML_MODEL_MEM
extern const uint8_t {name}_model_bin[];
#else
extern uint8_t {name}_model_bin[];
#endif
#define {name}_MODEL_BIN_LEN ({len(model)}u)
#define {name}_ARENA_SIZE ({arena_size}u)
#endif
"""
    source = f"""/* Generated by tools/generate_terrain_artifacts.py; {provenance}. */
#include "{stem}.h"
#ifdef CY_ML_MODEL_MEM
#include "cy_utils.h"
#define Q(x) #x
#define QUOTE(x) Q(x)
CY_SECTION(QUOTE(CY_ML_MODEL_MEM))
const
#endif
uint8_t {name}_model_bin[{name}_MODEL_BIN_LEN] __attribute__((aligned(16))) = {{
{c_bytes(model)}
}};
"""
    (MODEL_DIR / f"{stem}.h").write_text(header, encoding="utf-8")
    (MODEL_DIR / f"{stem}.c").write_text(source, encoding="utf-8")


def write_regression(name: str, quantized: np.ndarray, output: np.ndarray) -> None:
    # mtb_ml_x_file_header_t: INT8=2, one sample, 500 elements, non-RNN=-1.
    x_data = struct.pack("<iiii", 2, 1, int(quantized.size), -1) + quantized.tobytes()
    y_data = output.tobytes()
    for kind, values in (("x", x_data), ("y", y_data)):
        stem = f"{name}_tflm_{kind}_data_int8x8"
        symbol = f"{name}_{kind}_data_bin"
        guard = f"{stem.upper()}_H"
        header = f"""/* Generated fixed Host regression tensor; dataset sample {SAMPLE_INDEX}. */
#ifndef {guard}
#define {guard}
#include <stdint.h>
extern const uint8_t {symbol}[];
#define {name}_{kind.upper()}_DATA_BIN_LEN ({len(values)}u)
#endif
"""
        source = f"""/* Generated fixed Host regression tensor; dataset sample {SAMPLE_INDEX}. */
#include "{stem}.h"
const uint8_t {symbol}[{name}_{kind.upper()}_DATA_BIN_LEN] __attribute__((aligned(4))) = {{
{c_bytes(values)}
}};
"""
        (DATA_DIR / f"{stem}.h").write_text(header, encoding="utf-8")
        (DATA_DIR / f"{stem}.c").write_text(source, encoding="utf-8")


def host_golden() -> tuple[np.ndarray, np.ndarray, dict[str, object]]:
    os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
    import tensorflow as tf

    with np.load(DATASET, allow_pickle=False) as dataset:
        x = np.asarray(dataset["X"][SAMPLE_INDEX], dtype=np.float32)
        label = int(dataset["y"][SAMPLE_INDEX])
        split = str(dataset["split"][SAMPLE_INDEX])
        family = str(dataset["surface_family"][SAMPLE_INDEX])
    stats = json.loads(NORMALIZATION.read_text(encoding="utf-8"))["noisy/fusion"]
    standardized = (x - np.asarray(stats["mean"], np.float32)) / np.asarray(
        stats["std"], np.float32
    )
    interpreter = tf.lite.Interpreter(model_path=str(MODEL))
    interpreter.allocate_tensors()
    input_detail = interpreter.get_input_details()[0]
    output_detail = interpreter.get_output_details()[0]
    input_scale, input_zero_point = input_detail["quantization"]
    quantized = np.clip(
        np.rint(standardized / input_scale + input_zero_point), -128, 127
    ).astype(np.int8)[None, ...]
    interpreter.set_tensor(input_detail["index"], quantized)
    interpreter.invoke()
    output = np.asarray(interpreter.get_tensor(output_detail["index"]), np.int8)[0]
    if split != "test" or int(np.argmax(output)) != label:
        raise RuntimeError("fixed sample is not a correctly classified test sample")
    metadata = {
        "sample_index": SAMPLE_INDEX,
        "split": split,
        "surface_family": family,
        "expected_label": label,
        "expected_class": CLASS_NAMES[label],
        "input_shape": list(quantized.shape),
        "input_dtype": "int8",
        "input_scale": float(input_scale),
        "input_zero_point": int(input_zero_point),
        "input_sha256": hashlib.sha256(quantized.tobytes()).hexdigest(),
        "host_output_raw": output.tolist(),
        "host_class": int(np.argmax(output)),
        "output_scale": float(output_detail["quantization"][0]),
        "output_zero_point": int(output_detail["quantization"][1]),
    }
    return quantized, output, metadata


def vela_model() -> bytes:
    output_dir = REPORT_DIR / "vela"
    output_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "vela",
            str(MODEL),
            "--output-dir",
            str(output_dir),
            "--accelerator-config",
            "ethos-u55-128",
            "--optimise",
            "Performance",
            "--memory-mode",
            "Sram_Only",
            "--arena-cache-size",
            "2936012",
            "--show-cpu-operations",
        ],
        check=True,
    )
    return (output_dir / "noisy_fusion_int8_vela.tflite").read_bytes()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backend", choices=("cpu", "u55", "all"), default="all")
    args = parser.parse_args()
    if sha256(MODEL) != MODEL_SHA256 or sha256(DATASET) != DATASET_SHA256:
        raise RuntimeError("canonical model or dataset hash does not match the handoff")
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    quantized, output, metadata = host_golden()
    if args.backend in ("cpu", "all"):
        write_model("TERRAIN_CPU", MODEL.read_bytes(), 8192, "canonical raw strict-INT8 TFLite")
        write_regression("TERRAIN_CPU", quantized, output)
    if args.backend in ("u55", "all"):
        compiled = vela_model()
        write_model("TERRAIN_U55", compiled, 4096, "Vela 4.2.0, ethos-u55-128")
        write_regression("TERRAIN_U55", quantized, output)
        metadata["u55_model_size_bytes"] = len(compiled)
        metadata["u55_accelerator_config"] = "ethos-u55-128"
    metadata["source_model"] = str(MODEL)
    metadata["source_model_sha256"] = MODEL_SHA256
    metadata["source_dataset_sha256"] = DATASET_SHA256
    (REPORT_DIR / "fixed_test_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
