/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_Request, protocol_Request, AUTO)


PB_BIND(protocol_Response, protocol_Response, AUTO)


PB_BIND(protocol_BoardCapabilitiesRequest, protocol_BoardCapabilitiesRequest, AUTO)


PB_BIND(protocol_BoardCapabilitiesResponse, protocol_BoardCapabilitiesResponse, AUTO)


PB_BIND(protocol_OptionValue, protocol_OptionValue, AUTO)


PB_BIND(protocol_DeviceConfigurationRequest, protocol_DeviceConfigurationRequest, AUTO)


PB_BIND(protocol_DeviceConfigurationResponse, protocol_DeviceConfigurationResponse, AUTO)


PB_BIND(protocol_StartRequest, protocol_StartRequest, AUTO)


PB_BIND(protocol_StopRequest, protocol_StopRequest, AUTO)


PB_BIND(protocol_ResetRequest, protocol_ResetRequest, AUTO)


PB_BIND(protocol_DataChunk, protocol_DataChunk, AUTO)


PB_BIND(protocol_Timestamp, protocol_Timestamp, AUTO)


PB_BIND(protocol_DataInquire, protocol_DataInquire, AUTO)


PB_BIND(protocol_ErrorResponse, protocol_ErrorResponse, AUTO)


PB_BIND(protocol_WatchdogResetRequest, protocol_WatchdogResetRequest, AUTO)



