/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "model.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_Version, protocol_Version, AUTO)


PB_BIND(protocol_BoardSerial, protocol_BoardSerial, AUTO)


PB_BIND(protocol_Board, protocol_Board, AUTO)


PB_BIND(protocol_Device, protocol_Device, AUTO)


PB_BIND(protocol_Option, protocol_Option, AUTO)


PB_BIND(protocol_StreamConfig, protocol_StreamConfig, AUTO)


PB_BIND(protocol_Dimension, protocol_Dimension, AUTO)


PB_BIND(protocol_OptionInt, protocol_OptionInt, AUTO)


PB_BIND(protocol_OptionFloat, protocol_OptionFloat, AUTO)


PB_BIND(protocol_OptionBool, protocol_OptionBool, AUTO)


PB_BIND(protocol_OptionOneOf, protocol_OptionOneOf, AUTO)


PB_BIND(protocol_OptionBlob, protocol_OptionBlob, AUTO)


PB_BIND(protocol_OptionString, protocol_OptionString, AUTO)


PB_BIND(protocol_OptionPassword, protocol_OptionPassword, AUTO)











